node('SLAVE') {

    stage('Code Check-Out'){
        git 'https://github.com/citb34/studentapp-ui.git'
    }

    stage("Compile") {
        sh '''
mvn compile
'''
    }
        stage('Code Quality Check') {
        sh '''
mvn sonar:sonar \
  -Dsonar.projectKey=studentapp-ui \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=0700c1d1c256244ff1b223a74e55f853641b8004
'''
    }
}    
